### ISSUE TITLE
Add ability to ignore all day events and "Available" Events

### ISSUE THREAD

**Issue by TeutonJon78** [camsteffen/polite#5]
It would be nice to have a feature to allow filtering of events from the calendar properties like all day events or busy/available.

**Comment by camsteffen** [comment]
All day events are already ignored if they are actually marked as "All day" in the calendar. I may need to add additional filtering for events that are over a threshold like 8 hours perhaps. I am planning to add an option for "Busy Events Only"

**Comment by camsteffen** [comment]
This is fixed in 1.4.3

**Comment by Rabadaf** [comment]
I hate to be "that guy", but I had been using Polite to keep my phone quiet while I'm at work (among other things), which is usually 9-10 hours. The 8 hour limit means that stopped working for me. Any way that limit could be user-set?
