### ISSUE TITLE
Option to control phone LED?

### ISSUE THREAD

**Issue by jscottee** [camsteffen/polite#9]
This is a small feature, but a nice touch: could we have an option to disable the LED during a session?

I use a slightly older Samsung phone, so none of that LED customization present in the newer models. Since there are other apps that allow for that customization, an LED disable option would be nice for those who want to take away the distraction, but still have their phone face-up (e.g., using the "Always On" Samsung feature).

**Comment by camsteffen** [comment]
I don't think this is possible with the Android SDK. Unless you mean disabling the light specifically for the Polite notification. But I don't think the Polite notification should be turning on the LED.

**Comment by jscottee** [comment]
I mean disabling the LED entirely during a Polite session, and then turning it back on when done. Since there is a Settings pane to do that, I thought it might be able to be controlled by an app, too. For example, I use the Android "Always On display" and like looking at my phone, face up, to see the time and any new notifications. However, I find the blinking LED too distracting (which is by design).

I imagine the answer to this question might be around [here](https://developer.android.com/work/dpc/device-management) or on a related page. I have no experience with Android SDK, so I don't know if I'm looking in the right place.

**Comment by camsteffen** [comment]
Yeah, I'm not able to find anything except this [SO question](https://stackoverflow.com/questions/28754881/how-to-enable-or-disable-the-notification-led-in-android).

**Comment by jscottee** [comment]
Ah, should have checked SO first. My mistake.

**Comment by camsteffen** [comment]
No worries.
